### ISSUE TITLE
Cannot use object as an array

### ISSUE THREAD

**Issue by xmeltrut** [jayS-de/HandlebarsBundle#2]
I tried to loop through an array of Doctrine entities and output values from each one. However, in Symfony3, it throws an exception:

    Error: Cannot use object of type AppBundle\Entity\Word as array

It looks like it is trying to treat the object as an array when detecting if the property exists.

**Comment by jayS-de** [comment]
The handlebars engine lightncandy is best used with arrays as view data. The object resolver will cost a lot of performance. So you first have to convert your DoctrineEntity to an array.

Another possibility would be to add some options to the service "handlebars". See HandlebarsEnvironment and https://github.com/zordius/lightncandy/ FLAG_PROPERTY, FLAG_METHOD and FLAG_INSTANCE

**Comment by jayS-de** [comment]
Hi again,

I just added the possibility to set different compiler flags using the symfony configuration. You could try how it works with the current develop branch
